### ISSUE TITLE
Release stable version?

### ISSUE THREAD

**Issue by cmeeren** [elmish/react#41]
Since new major stable versions of Fable.Core and Fable.React have finally been released, it would be great if we could get stable versions of the Elmish packages (Fable.Elmish.React, Fable.Elmish.Browser, Fable.Elmish.Debugger, and perhaps others?)

~The above three packages are dependencies of [Fable.MaterialUI](https://github.com/mvsmal/fable-material-ui), and I'd like to submit a PR to update it to support the new Fable.Core and Fable.React versions, but AFAIK due to nuget rules, a new stable version of Fable.MaterialUI can't be released until all dependencies are out of beta.~ **Update:** False alarm, those are only used for the library's docs, not the package itself.

**Comment by et1975** [comment]
Yes, planning to release everything as stable this week.

**Comment by cmeeren** [comment]
Great, thanks for the quick reply!
